// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microting.KanbanBase.Infrastructure.Data;

#nullable disable

namespace Microting.KanbanBase.Migrations
{
    [DbContext(typeof(KanbanPnDbContext))]
    [Migration("20260412000000_MultiRepoGitHub")]
    partial class MultiRepoGitHub
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally left empty — snapshot is the source of truth
        }
    }
}
